### ISSUE TITLE
Include error logs into slack conversation

### ISSUE THREAD

**Issue by dsenecalb** [ashwanthkumar/gocd-slack-build-notifier#10]
Hi, 

When running a build in go-cd, the slack plugin provides the status of the pipeline stage to slack. However, when the status is failed or canceled, a log with the error must be sent to the channel as well.
Also, who ran the pipeline must be provided to the channel as well.

Thanks

**Comment by dsenecalb** [comment]
Looking into the slack chat, I found this from go 

Couldn't fetch build details; see server log.

Is there a way to remove this issue? Thanks

**Comment by ashwanthkumar** [comment]
@dsenecalb The latest release [v1.4.0-RC3](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.4.0-RC3) has links to the console logs of all the jobs in the stage. See if something like that would be useful.

**Comment by ashwanthkumar** [comment]
Closing this. Please re-open if the issue still exist.
