### ISSUE TITLE
GoCD 19.10.0 error with plugin 1.4.0

### ISSUE THREAD

**Issue by andriymarchuk** [ashwanthkumar/gocd-slack-build-notifier#101]
Configuration
GoCD Version : 19.10.0
Plugin Version : 1.4.0

Error
Following error occurs :

Notification update failed for plugin: slack.notifier23 Nov, 2019 at 17:47:55 Local Time
javax/xml/bind/DatatypeConverter

Context
I just upgraded GoCD  from 19.4.0 to 19.10.0 and this error occurred.

looks like the similar issue to https://github.com/ashwanthkumar/gocd-slack-build-notifier/issues/95

**Comment by arvindsv** [comment]
Yes. It's the same as #95. [Release v1.4.0-RC12](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.4.0-RC12) should work.

**Comment by andriymarchuk** [comment]
Unfortunately, this does not work. Also I have  tried latest release

**Comment by andriymarchuk** [comment]
bash-4.4$ /gocd-jre/bin/java --version
openjdk 13 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)

**Comment by arvindsv** [comment]
Just for the record, I tried it with OpenJDK 13 and it worked fine for me.

Plugin version: 1.4.0-RC11
GoCD version: 19.10.0

```
$ java -version
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)
```

**Comment by ashwanthkumar** [comment]
Closing this for now. @andriymarchuk If you still have the issue, please feel free to re-open the issue.
