### ISSUE TITLE
Bearer token is base64 encoded and should be used 'raw'

### ISSUE THREAD

**Issue by tobywan** [ashwanthkumar/gocd-slack-build-notifier#105]
Hi,

According to 

https://api.gocd.org/current/#authentication

we should use the api token like this:

``` bash
# With shell, you can just pass the correct header with each request
$ curl 'https://ci.example.com/go/api/current_user' \
      -H 'Authorization: bearer YOUR_TOKEN' \
      -H 'Accept: application/vnd.go.cd.v1+json'
```

Testing with curl confirms I can talk to my local gocd server.

However in src/main/java/in/ashwanthkumar/gocd/slack/jsonapi/Server.java
the bearer token is base64 encoded:

``` java
        if (isNotEmpty(mRules.getGoAPIToken())) {
            String bearerToken = "Bearer "
                    + DatatypeConverter.printBase64Binary(mRules.getGoAPIToken().getBytes());
            request.setRequestProperty("Authorization", bearerToken);
```
Configuring my go_notify.conf to use the api-token that worked above, results in a 401 error from gocd.
Setting it to use username/password works.

Also the docs specify an all lowercase `bearer` string

GoCD Version: 19.9.0 (10194-34fca8f7682a65ef5fbd6726d51fd52b0c041bc6).

Thanks

**Comment by bwalendz** [comment]
I have the same issue.

**Comment by nicolaasuni** [comment]
I have fixed this in https://github.com/ashwanthkumar/gocd-slack-build-notifier/pull/104

@ashwanthkumar Would you be able to review and merge these fixes?

**Comment by ashwanthkumar** [comment]
This is now fixed and released as part of https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v2.0.0. 

Thanks @nicolaasuni
