### ISSUE TITLE
go_notify.conf must be at the go-server directory

### ISSUE THREAD

**Issue by dsenecalb** [ashwanthkumar/gocd-slack-build-notifier#11]
Hi,

Running the plugin is awesome. However, setting the go_notify.conf at the home directory of the user running go can break things in terms of migrating the application (GoCD) to another server. Instead, I suggest to save the file into the go-server directory path.

**Comment by carlittle** [comment]
I would agree.  This fails if running go server on a Windows machine because the service does not have access to the home directory of the user.  I would suggest using the environment variable CRUISE_SERVER_DIR which on windows is the base directory where the Go Server is installed.

**Comment by manojlds** [comment]
+1

Set a sane default, and make it overridable with an environment variable?

**Comment by ashwanthkumar** [comment]
This is now available as part of [1.4.0-RC5](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.4.0-RC5). Please do give it a spin and share feedback.
