### ISSUE TITLE
Craft a new release after MS Teams PR

### ISSUE THREAD

**Issue by marcogreiveldinger** [ashwanthkumar/gocd-slack-build-notifier#115]
Hi together,

after PR #112 support for Teams was added. Would it be possible to release a jar with this changes included, so I could use it easily in my gocd instance?

Thanks and best regards!

**Comment by ashwanthkumar** [comment]
Forgot to post about it in here, this is not released and available on the latest release: https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v2.1.0
