### ISSUE TITLE
Include pipeline label in message notification?

### ISSUE THREAD

**Issue by mattcl** [ashwanthkumar/gocd-slack-build-notifier#12]
I currently use the git revision number as the pipeline label, and it would be useful to display this so I can tell which revision has just passed a certain stage.

**Comment by ashwanthkumar** [comment]
@srinivasupadhya Quick question. Does Notification API return pipeline label as part of its response? I saw [this](https://github.com/gocd/gocd/pull/968#issue-62772385) and couldn't find it.

**Comment by srinivasupadhya** [comment]
no. the `pipeline label` was dropped from payload to simplify/reduce DB query time.

**Comment by ashwanthkumar** [comment]
Is there a way we can query for that information from the plugin? Or is making an API call the only way?

**Comment by ashwanthkumar** [comment]
@mattcl The latest version [v1.4.0-RC3](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.4.0-RC3) has pipeline label in it's output message. Closing this issue.
