### ISSUE TITLE
Send notifications for each matching rule, not just the first

### ISSUE THREAD

**Issue by kennethkalmer** [ashwanthkumar/gocd-slack-build-notifier#19]
With the following configuration I expected that we'll only get _recoveries_ published in our main channel and the nitty gritty details in individual rooms we run per service.

```
  pipelines = [{
    name = ".*"
    stage = ".*"
    state = "failed|broken|fixed"
  },
  {
    name = "some-api"
    stage = ".*"
    state = "all"
    channel = "#some-api"
  },
  # ... More pipelines like *some-api*
  ]
```

Instead only the first rule got matched and the rest not. If this behaviour is desirable I can take a stab at a PR to get it in.

**Comment by ashwanthkumar** [comment]
cc: @sriram-r

**Comment by jdavisp3** [comment]
👍 to this feature, applying all matching rules would allow much more flexibility.

**Comment by jdavisp3** [comment]
We could preserve backwards compatibility by making this an optional feature, or adding a boolean flag, default false, to a rule that says to continue processing other rules even if this one applies.
