### ISSUE TITLE
Allow http(s)_proxy config variable in config and used downstream in slack notification library

### ISSUE THREAD

**Issue by rzenker** [ashwanthkumar/gocd-slack-build-notifier#2]
In an environment that does not allow direct access to hooks.slack.com an http proxy is needed.

Could you add support so that only the slack plugin/backend slack library would set it explicitly off of a config variable in the standard config file for this plugin?

If the go-server start script is modified to define it globally for java, it would affect all http(s) calls by go-server/other plugins.

**Comment by GenoZhou** [comment]
@rzenker @ashwanthkumar 
Just wonder how could we config it globally for java?
I tried having following context in /etc/default/go-server and restart go-server:

export JAVA_FLAGS="-Dhttp.proxyHost=http://proxy.xxx.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=http://proxy.xxx.com -Dhttps.proxyPort=8080"

but it does not work.

**Comment by ashwanthkumar** [comment]
@GenoZhou Can you try these settings
```
export SERVER_STARTUP_ARGS+=("-Dhttp.proxyHost=http://proxy.xxx.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=http://proxy.xxx.com -Dhttps.proxyPort=8080")
```
in your `/etc/default/go-server`

**Comment by ashwanthkumar** [comment]
@GenoZhou Can you try these settings

```
export GO_SERVER_SYSTEM_PROPERTIES="-Dhttp.proxyHost=http://proxy.xxx.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=http://proxy.xxx.com -Dhttps.proxyPort=8080"
```

in your `/etc/default/go-server`

**Comment by ashwanthkumar** [comment]
@rzenker @GenoZhou I just published [v1.4.0-RC1](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.4.0-RC1) which has support for providing proxy settings within the configuration file. Please do try it out and let me know if you still have issues.

**Comment by GenoZhou** [comment]
It shows another error:

Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"status":"failure","messages":["sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"]}']

**Comment by ashwanthkumar** [comment]
What's your version of JVM? If it's JDK6 - it might be similar to this issue - http://stackoverflow.com/a/21507568.
