### ISSUE TITLE
Reload config at interval or at event time

### ISSUE THREAD

**Issue by manojlds** [ashwanthkumar/gocd-slack-build-notifier#24]
Restarting Go server is very costly in most setups.

**Comment by dayglojesus** [comment]
:+1:

**Comment by just2jays** [comment]
🙌 +1

**Comment by marcinkubica** [comment]
+1 maybe api call?

**Comment by praveenselvam** [comment]
👍  +1

**Comment by ashwanthkumar** [comment]
I've a branch for this feature. If anyone wants to give it a spin and share feedback, you're most welcome 😸  - https://github.com/ashwanthkumar/gocd-slack-build-notifier/pull/49

**Comment by ashwanthkumar** [comment]
Now available as part of [v1.4.0-RC2](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.4.0-RC2) release.
