### ISSUE TITLE
Separate internal and external go server urls

### ISSUE THREAD

**Issue by manojlds** [ashwanthkumar/gocd-slack-build-notifier#25]
Add settings `server-host-internal` and `server-host-external`.

Internal one should be used to fetch build information, and external one will be used in the Slack message.

Default both to `127.0.0.1`. Set one to the other, if only one of them is set.

**Comment by gregorygtseng** [comment]
Looks like https://github.com/ashwanthkumar/gocd-slack-build-notifier/pull/39 basically solves this issue! @WeiBanjo
