### ISSUE TITLE
Use of Slack Token Vice Username/Password

### ISSUE THREAD

**Issue by seanhumbarger** [ashwanthkumar/gocd-slack-build-notifier#27]
Any plans on implementing the use of slack tokens as opposed to hardcoding plaintext username/password in the conf file?

**Comment by grahamc** [comment]
Hi Humbargs, the login and password in the configuration file isn't for Slack, it is for the Go server. The plugin already takes a webhook URL -- not a username, password, or even a token.

**Comment by seanhumbarger** [comment]
Thanks!  Sorry for the confusion!

**Comment by grahamc** [comment]
No worries, cheers!
