### ISSUE TITLE
FIX notfications on every successful build

### ISSUE THREAD

**Issue by TheCodeKing** [ashwanthkumar/gocd-slack-build-notifier#32]
We set up the plug-in to send notifications for `failed` only. However on every build we get a FIXED notification regardless of the previous run.

`pipelines = [{
    name = "pipeline"
    stage = "Stage|OtherStage"
    state = "failed"
    channel = "#channel"
  }]`

**Comment by ashwanthkumar** [comment]
Fixed via #33
