### ISSUE TITLE
Ability to post notifications to different channels

### ISSUE THREAD

**Issue by TheCodeKing** [ashwanthkumar/gocd-slack-build-notifier#35]
It would be great if we could have the ability to post to multiple Slack channels based on the pipeline and status rules. The current config only allows one global service hook.

**Comment by ashwanthkumar** [comment]
@TheCodeKing Do you want a single pipeline status message to go to multiple slack channels or ability to choose different channels for different pipelines? If it's the latter, you can do that today - Taking a snippet of the config from the README. 

```
  pipelines = [{
    name = "gocd-slack-build"
    stage = "build"
    state = "failed|passed"
    channel = "#oss-build-group"
  }]
```

**Comment by TheCodeKing** [comment]
It was actually the later, and after I posted I noticed the config setting. However when setting up a Slack service hook, I can only set one destination channel. Maybe I'm missing something?

**Comment by ashwanthkumar** [comment]
@TheCodeKing On Slack, the channel you configure is the default channel for the webhook but Slack allows you to [override these settings](https://api.slack.com/incoming-webhooks#customizations_for_custom_integrations).

**Comment by TheCodeKing** [comment]
Thanks, I meant in slack. Is it possible for a Slack service hook have access to multiple channels? When I set it up it only allows me to select one.

**Comment by ashwanthkumar** [comment]
Yes it's possible. As long as you've a webhook you can post to anyone / channel / private group.

**Comment by TheCodeKing** [comment]
Ok thanks! That's where the confusion is coming from, sorry I'm new to Slack WebHooks. It must be a default.

**Comment by ashwanthkumar** [comment]
Closing the issue.
