### ISSUE TITLE
GoCD (16.3.0) error with plugin (1.2.2)

### ISSUE THREAD

**Issue by callumslab** [ashwanthkumar/gocd-slack-build-notifier#42]
Hi Ashwanth,

As requested, I've encountered an error in GoCD when using your plugin and the above version numbers.

The error I receive in GoCD console is: Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"status":"failure"}']

My GoCD server is running on a Server 2012R2 box in AWS.

I've attached my config and logs for review.

I can't consistently replicate the issue as it only sometimes happens, usually part way through a pipeline where it will just stop sending messages to Slack.

The error of interest as you pointed out is: On April 27, "java.lang.NullPointerException   at in.ashwanthkumar.gocd.slack.GoNotificationMessage.tryToFixStageResult(GoNotificationMessage.java:187)"

[go-server.txt](https://github.com/ashwanthkumar/gocd-slack-build-notifier/files/240728/go-server.txt)
[plugin-slack.notifier.txt](https://github.com/ashwanthkumar/gocd-slack-build-notifier/files/240729/plugin-slack.notifier.txt)
[go_notify.txt](https://github.com/ashwanthkumar/gocd-slack-build-notifier/files/240741/go_notify.txt)

Sorry for the lack of .zip, Github didn't like my .zip file.

**Comment by comanteodormihai** [comment]
Hey, i ve got the same error from time to time inside go. As above, is not a constant error, is just from time to time and only on failures.

Well done with the plugin never the less :+1:

**Comment by vmpj** [comment]
My integration seems to be totally broken by this error

**Comment by kevynb** [comment]
Actually, the error happens when you a build pass on a previously failing pipeline, thus fixing the pipeline.
To reproduce the error, you need to 'help' a pipeline to fail, and then fix the pipeline. Maybe there's more because it seems the error happens because the information we have in the plugin's history varialbe is not right
