### ISSUE TITLE
plugin failure for 16.1.0 gocd version

### ISSUE THREAD

**Issue by chakrapani123** [ashwanthkumar/gocd-slack-build-notifier#44]
error message:

WARN [67@MessageListener for PluginNotificationListener] PipelineListener:62 - Couldn't find any matching rule of 

and no slack notifications are pushed to channel .

**Comment by ashwanthkumar** [comment]
@chakrapani123 Looks like there aren't any rules matching for the pipeline that just ran. Can you share the configuration and the pipeline name, stage name and job name of the pipeline that ran?

**Comment by chakrapani123** [comment]
2016-05-26 14:15:49,386  INFO [67@MessageListener for
PluginNotificationListener] Server:52 - Fetching http://gocd-server:

8153/go/api/pipelines/create-service-pipelines/history

2016-05-26 14:15:50,529  WARN [67@MessageListener for
PluginNotificationListener] PipelineListener:62 - Couldn't find any
matching rule for cre

ate-service-pipelines/create-pipelines with status=Passed

here is a snippet from config : (modified)

<pipeline name="create-service-pipelines" isLocked="false">

```
  <environmentvariables>

    <variable name="service">

      <value>aXXXXXXX</value>

    </variable>

    <variable name="version">

      <value>X</value>

    </variable>

  </environmentvariables>

  <materials>

    <git url="XXXXXXXX" autoUpdate="false" materialName="source" />

  </materials>

  <stage name="create-pipelines" cleanWorkingDir="true">

    <approval type="manual" />

    <environmentvariables>

      <variable name="service">

        <value>some-service</value>

      </variable>

      <variable name="version">

        <value>X</value>

      </variable>

    </environmentvariables>

    <jobs>

      <job name="create">

        <tasks>

          <task>

            <pluginConfiguration id="script-executor" version="1" />

            <configuration>

              <property>

                <key>script</key>

                <value>XXXXX</value>

              </property>

            </configuration>

            <runif status="passed" />

          </task>

        </tasks>

        <resources>

          <resource>create-service</resource>

        </resources>

      </job>

    </jobs>

  </stage>

</pipeline>
```

**Comment by ashwanthkumar** [comment]
Thanks @chakrapani123. Can you also please share the slack plugin configuration?

**Comment by ashwanthkumar** [comment]
The `go_notify.conf` file contents. Please feel free to mask out the slack webhook and gocd credentials from the file.

**Comment by chakrapani123** [comment]
slack-notifier - gocd-slack-notifier-1.1.2.jar

go-server home directory - /app/go-server

go directory - /app/home/go

pipelines directory - /app/go-server/pipelines

artifacts - /app/go-server/artifacts

plugins - /app/go-server/plugins

list of other plugins installed on gocd-server:

script-executor-0.2.jar

gocd-gradle-plugin-1.0.4.jar

docker-task-assembly-0.1.23.jar

springer-gocd-cloudfoundry-plugin-2.0.0.jar

gocd-maven-plugin-0.1.1.jar

go-plugin-groovy-1.0.1.jar

java - 1.8.0_40

goad-slack-notifier location :
/app/go-server/plugins/external/gocd-slack-notifier-1.1.2.jar

i have copied go_notify & gocd.slack.pipelines in /app/home/go ,
/app/go-server  & /var/go as well

go_notify :

gocd.slack {

  login = "XXXX"

  password = "XXXX"

  server-host = "http://gocd-server:8153/"

  api-server-host = "http://gocd-server:8153/"

  webhookUrl = "https://hooks.slack.com/services/......."

  # optional fields

  #channel = "#build"

  #slackDisplayName = "gocd-slack-bot"

  #slackUserIconURL = "http://example.com/slack-bot.png"

}

gocd.slack.pipelines:

gocd.slack {

  login = "XXXX"

  password = "XXXXX"

  server-host = "http://gocd-server:8153/"

  api-server-host = "http://gocd-server:8153/"

  webhookUrl = "https://hooks.slack.com/services/......."

  # optional fields

  #channel = "#build"

  #slackDisplayName = "gocd-slack-bot"

  #slackUserIconURL = "http://example.com/slack-bot.png"

}

/etc/default/go-server :

export GO_SERVER_PORT=8153

export GO_SERVER_SSL_PORT=8154

export JAVA_HOME=/app/platform/java/jdk1.8.0_40

export SERVER_WORK_DIR=/app/go-server

DAEMON=Y

VNC=N

export JAVA_HOME="/app/platform/java/jdk1.8.0_40"

i have tested webhooks url with a simple curl post and it works fine

 curl -X POST --data-urlencode 'payload={"channel": "#gocd", "username":
"webhookbot", "text": "This is posted to #gocd and comes from a bot named
webhookbot.", "icon_emoji": ":ghost:"}' https://hooks.slack.com/services/......
.......

**Comment by ashwanthkumar** [comment]
@chakrapani123 As you can see on the README (https://github.com/ashwanthkumar/gocd-slack-build-notifier#pipline-rules), the default notification pipeline rules is to send the notifications only on pipeline failures. From the log you posed before, the stage in the pipeline actually passed. Can you try these things for me please?
1. Create a new pipeline, with a dummy stage which does `exit 1`. This will ensure that when the pipeline runs, the pipeline fails and it should trigger a post to Slack. 
2. Can you please add the `pipelines` config sections to the configuration (as specified on https://github.com/ashwanthkumar/gocd-slack-build-notifier#pipline-rules) to your `go_notify.conf` ?

Please try the above and let me know if that helps.

**Comment by chakrapani123** [comment]
it works now . thanks so much for gocd-slack-plugin. thanks
