### ISSUE TITLE
The plugin does not recognize a logged user and notifications all come through as 'anonymous'

### ISSUE THREAD

**Issue by navidhaghju** [ashwanthkumar/gocd-slack-build-notifier#48]
This by no means is a big issue, but it'd be nice to see who triggered the build in the Slack channel too.

**Comment by ashwanthkumar** [comment]
@navidhaghju Thanks for reporting the issue. I've fixed that as part of [v1.4.0-RC3](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.4.0-RC3) release. Can you please give it a shot and let me know? Thanks.

**Comment by navidhaghju** [comment]
@ashwanthkumar Thank you very much! Just tried the new version and it works like a charm :-) and notifications are much cleaner :+1:
