### ISSUE TITLE
Allow for multiple teams (webhooks) within the config

### ISSUE THREAD

**Issue by saundersjr** [ashwanthkumar/gocd-slack-build-notifier#51]
I would like to add multiple teams (webhooks) to the config, and thus route slack notifications between the teams.

I did try multiple configs (e.g. gocd.slack {...} ), but found only the latter config was used.

**Comment by ashwanthkumar** [comment]
Just so I understand this right, you want to support multiple slack teams for every notification or different slack teams for different notifications?

**Comment by ashwanthkumar** [comment]
If it's the latter, try out the new [1.4.0-RC7](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.4.0-RC7) release and let me know if that's what you're looking for.

**Comment by saundersjr** [comment]
It is the later.  I want to send notifications for different pipelines to
channels in different teams(webhooks).

I will try the latest version and get back to you.

Regards,

Julian

**Comment by saundersjr** [comment]
The new version seems to be working as expected.

Thank you.
