### ISSUE TITLE
Getting notifications to work.

### ISSUE THREAD

**Issue by michaeloa** [ashwanthkumar/gocd-slack-build-notifier#52]
Trying to run this in gocd 16.7. Not seeing any notifications in slack

My go_notify.conf looks as follows:

```
gocd.slack {
  login = "admin"
  password = "mypassword"
  server-host = "https://gocd.met.no/"
  api-server-host = "http://localhost:8153/"
  webhookUrl = "https://hooks.slack.com/services/mywebhook-etc"

  pipelines = [{
    name = "."
    stage = "."
    state = "all"
  }]

  # optional fields
  channel = "#gocd"
  slackDisplayName = "gocd-bot"
  displayMaterialChanges = true
}
```

The user/passsword works. The webhookUrl has been created in Slack. However, no notifications in slack, and no output in the log. What have I done wrong?

**Comment by ashwanthkumar** [comment]
The pipeline configurations are regex params. Try this configuration

```
gocd.slack {
  login = "admin"
  password = "mypassword"
  server-host = "https://gocd.met.no/"
  api-server-host = "http://localhost:8153/"
  webhookUrl = "https://hooks.slack.com/services/mywebhook-etc"

  pipelines = [{
    name = ".*"
    stage = ".*"
    state = "all"
  }]

  # optional fields
  channel = "#gocd"
  slackDisplayName = "gocd-bot"
  displayMaterialChanges = true
}
```

Very similar to the example in the [README](https://github.com/ashwanthkumar/gocd-slack-build-notifier#pipeline-rules).

**Comment by micabytes** [comment]
Hmm. I had actually set that in the GUI interface, but that did not seem to work. Editing the conf file worked.

Anwyay, works now. Excellent plugin.

**Comment by micabytes** [comment]
Ah... I realize now why the pipeline settings in the UI weren't working. I'm creating go_notify,conf via Chef in our server setup, so all of the changes that I put into the UI get overriden by Chef.

On the other hand, I can't not generate the file via Chef, because then I can't bootstrap a new server correctly (go_notify.conf would be missing).

May I suggest making the plugin 100% configurable from the web UI (webhook, server-host, login/password, etc., so that it is no longer necessary to generate the go_notify.conf by hand/provisioning system.

**Comment by michaeloa** [comment]
Sorry - logged in under my other ID.

Anyway - it turned out that I had actually set the settings correctly in the UI, but they weren't working (although showing up "correctly" in the UI) because I was creating go_notify,conf via Chef in our server setup, so all of the changes that I put into the UI get overriden by Chef. Once I switched the template in Chef to the correct settings, things worked as expected.

May I suggest making the plugin 100% configurable from the web UI (webhook, server-host, login/password, etc., so that it is no longer necessary to generate the go_notify.conf by hand/provisioning system.

As it is, the UI is not useful if this is set up via Chef or another auto-provisioning system. In the case of Chef, I have to let it create the go_notify.conf file, otherwise I would have to do so manually when I bootstrap a new server.

Alternatively split the notification settings from the plugin setup settings so that stuff like passwords etc can be bootstrapped without messing around in the same file as the notification setitngs.

Apart from that - excellent plugin.

**Comment by ashwanthkumar** [comment]
@michaeloa Oops sorry for the trouble. I thought I had a [banner on the UI](https://github.com/ashwanthkumar/gocd-slack-build-notifier/blob/master/src/main/resources/views/config.template.html#L3) that said the values are for demonstration only and it's actually not used by the plugin. 

The UI was created to avoid a specific exception that GoCD was throwing when the config page was not implemented by notification plugins. Many users misunderstood that to be an issue with the plugin. That's also the reason why I don't talk about the UI configuration in the README as well, but apparently neither the banner nor the missing documentation has helped here. Need to find out a better way to do that. Though I'm currently working on a [UI for the plugin](), i'm still not so confident that's the right way to go. 

We also use Chef in our infrastructure and I find it super useful to manage the configuration via Chef. Developers when they want to change the settings, just send in PRs to our chef repo and it get's reflected within the next 30 min. The settings are automatically read by the plugin upon change without a server restart (similar to #24). 

On the feedback of splitting notification settings and the plugin setup settings - Given we're still based on the configuration file I would like to keep it that way. May be once we move to other ways of configurations, we might want to do as you suggested. May I suggest you create a separate issue just for that? I'm thinking of renaming this issue to fix the plugin UI to reflect that it's clearly not being used. Your thoughts?

**Comment by michaeloa** [comment]
Ha - you are right, it does say that. Though (at least on my browser), this is just some small subtext below the window title, so I'm not surprised that I entirely overlooked it.

 Also, from my UI experiences, never assume that people read anything unless it is in 100pt text on a red flashing background. And sometimes not even then. :-D

I think based on what you mention, I would actually prefer it if there wasn't as UI, or that the UI window just contained some helpful documentation text. I'm pretty OK with managing the configuration through Chef in this case anyway, Always good to have things in a VCS. Don't think a UI is really needed - it's easy enough to configure the plugin once I realized my error(s). Wouldn't want people messing around in the CD system who can't do a PR anyway.

Feel free to rename the issue or close it, whatever suits your purposes. I/we're OK, now. Thanks for the help.

**Comment by michaeloa** [comment]
So, this is still not working exactly as expected. I have a go_notify.conf set up through Chef that looks as follows (local_user inserted via Chef):

```
gocd.slack {
  login = "<%=@local_user['username']%>"
  password = "<%=@local_user['password_clear']%>"
  server-host = "https://gocd.my.server/"
  api-server-host = "http://localhost:8153/"
  webhookUrl = "https://hooks.slack.com/services/webhook..."

  pipelines = [{
    name = "proj1"
    stage = "deploy"
    state = "passed"
    owners = ["person0"]
  },
  {
    name = "proj_2"
    stage = "smoketest"
    state = "passed"
    owners = ["person1", "person2"]
  },  
  {
    name = "proj_3"
    stage = "deploy_to_routine"
    state = "passed"
    owners = ["person1", "person2"]
  },  
  {
    name = ".*"
    stage = ".*"
    state = "failed"
  }]

  # optional fields
  channel = "#gocd"
  slackDisplayName = "gocd-bot"
  displayMaterialChanges = true
}

```

If I understood this correctly, this should mean that we get notifications when proj_1, proj_2. and proj_3 go into production (i.e., pass the stages mentioned) + a notification if any stage fails. First part of that seems to work as expected, but slack does not seem to get notified for failed stages. Another simple mistake?

Also, what is the difference between "broken" and " failed" states?

**Comment by ashwanthkumar** [comment]
I think, you're hitting #19. So far I have not had a reason to implement that feature, but yours look like a valid use-case. Implementing that also means we loose backward compatibility with how the plugin works today. I was hoping to do that with 2.x version. 

To handle it for now, you can try something like

```
  pipelines = [{
    name = "proj1"
    stage = "deploy"
    state = "passed|failed|broken"
    owners = ["person0"]
  },
  {
    name = "proj_2"
    stage = "smoketest"
    state = "passed|failed|broken"
    owners = ["person1", "person2"]
  },  
  {
    name = "proj_3"
    stage = "deploy_to_routine"
    state = "passed|failed|broken"
    owners = ["person1", "person2"]
  },  
  {
    name = ".*"
    stage = ".*"
    state = "failed"
  }]
```

> Also, what is the difference between "broken" and " failed" states?

It's easier to visualise it with the following table

| Previous State | Current State | Result |
| --- | --- | --- |
| Passed | Passed | Passed |
| Failed | Failed | Failed |
| Passed | Failed | Broken |
| Failed | Passed | Fixed |
