### ISSUE TITLE
Send console log to Slack

### ISSUE THREAD

**Issue by zuriar** [ashwanthkumar/gocd-slack-build-notifier#54]
Hi

Is it possible to get hold of the build console log to attach it to a Slack message? I need a way to get the failed build console log to users who do not have login rights to GoCD.

Thanks
Hugh

**Comment by ashwanthkumar** [comment]
@zuriar Can you please explain the use case a little more? 
In the sense, adding users to GoCD is free right? Is there a reason for not creating access to users?

**Comment by zuriar** [comment]
@ashwanthkumar Sure, I have team members who should not have access to GoCD. We don't want them to. As far as I am aware, we can't lock them down to Read Only. If we could stop them from doing any changes in GO then it would be good - but still more desirable to just send the console log to a slack channel. We are using GO to build Docker images.

**Comment by ashwanthkumar** [comment]
@zuriar I had a debate on a similar topic with someone internally at my company too little while ago. The reason we decided not go with sending console.log file as attachments were
1. It encourages too much digital waste. The actual error message we're interested in are generally located in the last few lines of the console.log. For long running jobs, the console.log might tend to get bigger.
2. Today the plugin integrates to Slack using Incoming Webhook interface. Unfortunately, slack doesn't allow file uploads using this interface. 

For your specific use-case, you could create users with specific roles and allow them access to specific pipeline groups. We follow the same approach in our organization for our external vendors. We have 1 / 2 separate pipeline groups and their gocd accounts have read-only access only to those pipelines. They can see the logs but not change the template / pipeline settings. Is that something that you might want consider given the above points?

**Comment by ashwanthkumar** [comment]
#59 enables log links in the slack message that's sent.
