### ISSUE TITLE
Not able to use a data url as the icon url

### ISSUE THREAD

**Issue by alethenorio** [ashwanthkumar/gocd-slack-build-notifier#55]
I am trying to set the `slackUserIconURL` as a data url so it does not have to go out on the internet and get some link which may or may not change.

I used this website to create a data url (http://dataurl.net/#dataurlmaker) and pasted the resulting url in my configuration file.

There was no exceptions or complaints from the plugin logs however the notifications had no image associated to it.

Is this some potential limitation on the plugin or slack?

I attempted this with both the svg and the png icons found here (https://brandfolder.com/s/oe9weu-3vl7eo-2mhqst)

**Comment by ashwanthkumar** [comment]
@ByteFlinger AFAIK it's something to do with slack - they don't support it last time I checked[1][2]. The plugin doesn't validate any data like icon urls - we just send it as is to slack. May be there's a new format, that I don't know of. If you can make it work using custom payload and share the attachment snippet - I can fix it for you in the plugin. 

Ref
[1] https://twitter.com/slackapi/status/563148421297483777
[2] https://api.slack.com/docs/message-attachments

**Comment by alethenorio** [comment]
Hi @ashwanthkumar 

I will have to look into it to see if the status of the issue has changed on slack side but I have little hope for it. :(

Thank you for the prompt reply

**Comment by ashwanthkumar** [comment]
@ByteFlinger I'm closing this issue for now. Feel free to re-open / comment back and I'll re-open the issue.
