### ISSUE TITLE
Print all changes instead of last 5

### ISSUE THREAD

**Issue by fire** [ashwanthkumar/gocd-slack-build-notifier#58]
Is it possible to print out all changes instead of the last 5?

**Comment by ashwanthkumar** [comment]
I can make that change, but do you think it would be useful? It's better done at GoCD's compare view - IMHO. What are your thoughts?

**Comment by fire** [comment]
In slack we have people that don't have access to perforce or gocd for QA, they would like to see the complete list of changes between builds and this would give them that.

It could be a default off toggle in the config because limiting the amount of text in the slack bot channel is important.

**Comment by ashwanthkumar** [comment]
@fire Okay. I can make the list of changes configurable in the configuration and have the default as 5 (the default behaviour). Or would you like it to be a switch which when toggled would dump entire list of changes across all materials or limit it to just 5?

**Comment by fire** [comment]
Perhaps a default of 5 and allow infinity for all changes. Not sure if you want to reuse 0. 

I need the ability to dump the entire changes. Limiting it to a number is not as important.

**Comment by fire** [comment]
Maybe have two [settings], one that defines the number of changes shown and the other which is show all changes. 

Show all changes overrides number of changes.

This is because I don't think there's a value in number of changes shown that can be the infinity value.

**Comment by fire** [comment]
A colleague said use -1 for infinite changes.

**Comment by ashwanthkumar** [comment]
I guess I'll go with just a toggle that would show either the default list of 5 or all changes - nobody seem to be asking for specifically `n` commits so far 😛

**Comment by fire** [comment]
That's all we need 👍

**Comment by fire** [comment]
@ashwanthkumar Are you still working on this?

**Comment by ashwanthkumar** [comment]
@fire I haven't started working on it yet. Would you like to take a stab at it?

**Comment by fire** [comment]
@ashwanthkumar Currently deep in release processes, so I'm not available. I'll look at the source code for curiosity though.

**Comment by fire** [comment]
poke

**Comment by ashwanthkumar** [comment]
@fire The changes for this are done and pending review (it's on #64 ). Do have a look and let me know your feedback. 

Once it's merged, will cut a release.

**Comment by ashwanthkumar** [comment]
@fire The release [v1.4.0-RC10](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.4.0-RC10) has this change. Please do try it out and let us know your feedback.

**Comment by fire** [comment]
Just installed it, will see what happens.

**Comment by fire** [comment]
Works great!
