### ISSUE TITLE
Release 1.4.0-RC9

### ISSUE THREAD

**Issue by jdavisp3** [ashwanthkumar/gocd-slack-build-notifier#61]
cc @ashwanthkumar How does this look:

https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/untagged-7b9139841cb2dfb651c8

**Comment by ashwanthkumar** [comment]
Looks great 👍 . Please also add SHA256 checksum of the JAR to the release page and also link to the PRs or issues that goes in the release. It would be easy to trace back how / who contributed the feature - I generally found that to be useful.

**Comment by jdavisp3** [comment]
Oh, right, how about now?

**Comment by jdavisp3** [comment]
https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/untagged-2e847c7470d1b0a1c34c

**Comment by ashwanthkumar** [comment]
Just perfect! 👍

**Comment by jdavisp3** [comment]
🚀 Thanks @ashwanthkumar !
