### ISSUE TITLE
Allow for matching pipeline groups

### ISSUE THREAD

**Issue by alethenorio** [ashwanthkumar/gocd-slack-build-notifier#65]
Would it be possible to match pipeline groups so that you can have rules per pipeline group rather than pipeline?

**Comment by ashwanthkumar** [comment]
@ByteFlinger The plugin targets 16.1 today which doesn't seem to have pipeline group in it's response. But from the oldest plugin API docs [that's available](https://plugin-api.go.cd/16.3.0/notifications/#stage-status-changed) (from 16.3.0) - it seems to have group information in the request body. So if we upgrade the Go version dependency - we might be able to support this feature.

**Comment by ashwanthkumar** [comment]
@ByteFlinger The new release [1.4.0-RC11](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.4.0-RC11) has this feature. Please do give it a shot and let us know your feedback.

**Comment by alethenorio** [comment]
Hi

I am not sure this is working as expected. I have been testing this for a while now but notifications just stopped coming.

I have a configuration like this (All values below are dummy)

```
gocd.slack {
  login = "gocd_login"
  password = "gocd_password"
  server-host = "http://gocd.host.com:8153"
  api-server-host = "http://localhost:8153/"
  webhookUrl = "https://hooks.slack.com/services/HSSSTSS/S4DN7AS/UHwf5HH7S"

  slackDisplayName = "gocd-slack-bot"
  slackUserIconURL = "https://api.go.cd/current/images/logo.png"

  displayMaterialChanges = true

  proxy {
    hostname = "192.168.2.3"
    port = "3128"
    type = "http" # acceptable values are http / socks
  }

  pipelines = [{
    name = ".*"
    stage = ".*"
    group = "Group1|Group2"
    state = "failed|fixed|broken"
    channel = "#somechannel"
    webhookUrl = "https://hooks.slack.com/services/HSSSTSS/S4DN7AS/UHwf5HH7S"
  },
  {
    name = ".*"
    stage = ".*"
    group = "Group3"
    state = "failed|fixed|broken"
    channel = "#otherchannel"
    webhookUrl = "https://hooks.slack.com/services/JSSTS/HgggH777/JJJ888kl9HHHFD4"
  }]
}
```

And yet I get no notification and this comes out in the logs

```
GoNotificationPlugin:52 - My-Pipeline/8/someStage/1 has Failed/Failed
Server:52 - Fetching http://localhost:8153/go/api/pipelines/My-Pipeline/history
PipelineListener:62 - Couldn't find any matching rule for My-Pipeline/someStage with status=Failed
```

My-Pipeline in this case is assigned to pipeline group Group1

Am I missing something? I got the feeling that it worked when I tested the first time but it has been quiet for a very long time now

**Comment by ashwanthkumar** [comment]
@ByteFlinger You might want to remove your actual webhook urls from the above comment. 
Also can you please check and let me know what version of plugin are you using along with the GoCD version too.

**Comment by alethenorio** [comment]
Hi

The hook URLs are dummies. They are not real. I left them there to show the exact layout of our config

We are used by Gocd 17.1 (upgraded to 17.2 today) and the version of the plugin is the latest 1.4.0-RC11.

I vaguely remember testing it before actual going ahead with it in production and it seemed to work but then it just got quiet

**Comment by alethenorio** [comment]
@ashwanthkumar Anything I can help to debug here?

**Comment by ashwanthkumar** [comment]
@ByteFlinger I tried running things locally and I'm not able to reproduce the issue. Can you please double-check if the proxy settings are right?

**Comment by alethenorio** [comment]
Hi @ashwanthkumar 

Sorry for the late reply here. I am certain the proxy settings are right, I have never changed them and I doubled checked now and everything is as expected. The logs imply that it simply does not think that there are any configurations for all the pipelines triggers that happen within go
