### ISSUE TITLE
Customizable Messages on notifications

### ISSUE THREAD

**Issue by ghost** [ashwanthkumar/gocd-slack-build-notifier#72]
Hi, is it possible to customize the message on the notifications? 
Like, for exemple, the bot says: "Hey Guys, the build is not alright. Here is the link:" ?
I cant find any configuration for that, and would be nice, more "friendly" :)

**Comment by ashwanthkumar** [comment]
@hbsis-williamdasilva Unfortunately we don't have support for it today 😞  Would you be kind enough to send a PR for the same? 

PS: I thought the current notification doesn't send any messages (only fields) to keep it delivery-neutral. Sorry you find it less friendly :(

**Comment by ghost** [comment]
@ashwanthkumar I'm reving this issue :D
I'll try to make a pull request. Maybe I'll just need some help to understand somethings. So can I ask if I find something difficult?
Also, I would like to hear your opinion about what I have in mind:
The same way you have rules on your config, for pipelines, you could have a custom message for each pipeline. 

I was trying somethings with slack webhook and could post messages with Postman using json and formatting provided by the slack website.

So my idea is a nullable field "customMessage" wich is a json. If the field is null, it will post the normal message. If there is a custom json, it will post the json. What do you think about it? :D

**Comment by ashwanthkumar** [comment]
@hbsis-williamdasilva Go for it 👍 I would be happy to review the changes and merge it in.

**Comment by ghost** [comment]
@ashwanthkumar Found something:
https://github.com/ashwanthkumar/slack-java-webhook/blob/master/src/main/java/in/ashwanthkumar/slack/webhook/service/SlackService.java

On this service, the message is built on the method push (line 36).
My initial idea is to pass a custom json on the pipeline rules, and this method push would receive this json without changing it and pass it to the execute method.
What do you think?

**Comment by ghost** [comment]
(@ashwanthkumar also, do I need permission to create a branch on your projects? What is the best way to commit for you? )

**Comment by ghost** [comment]
@ashwanthkumar So, I did the changes, here they are:
First, on the Slack Java Webhook, at the SlackService class, I did an overload of the method execute, to receive a string, wich will be our custom json:
![image](https://user-images.githubusercontent.com/23528701/39709620-c236e84c-51f0-11e8-8ec5-cdf8d6df904d.png)

After that, I did the same thing at the Slack class:
![image](https://user-images.githubusercontent.com/23528701/39709652-ddcd5a96-51f0-11e8-8075-c28b34d64ff0.png)

So now we can go to the notification plugin:

I created a new field in the PipelineRule class: "customMessage":
![image](https://user-images.githubusercontent.com/23528701/39709740-186d926a-51f1-11e8-8b83-028f7ce50977.png)

And then, in the SlackPipelineListener class, I checked first for the custom message before creating a slackAttachment:
![image](https://user-images.githubusercontent.com/23528701/39709826-52674b5a-51f1-11e8-97f8-9a7bce53318c.png)

So in this case, the customMessage that we got in our config file will be sent direct to slack:
![image](https://user-images.githubusercontent.com/23528701/39709897-8b0529fa-51f1-11e8-94c7-19e40f4add4a.png)

(the json in the config is supposed to send a message like this:)
![image](https://user-images.githubusercontent.com/23528701/39709922-9e1e7168-51f1-11e8-9a04-4b6c2428cb58.png)

The thing is, now I need your help.
I'm not a Java Guy (I work with C# and Visual Studio) so all this things, jar files, etc are kind of new to me. 
I still didn't test the changes.
How could I do that?
I thought that creating the new jar file and sending it to the go cd server would work but I got this error:
![image](https://user-images.githubusercontent.com/23528701/39709986-dbce364c-51f1-11e8-97ff-297127781da0.png)

I will wait for you to go on.
Thanks :D

**Comment by ghost** [comment]
@ashwanthkumar Asked for a friend to help me and we did it 👍 
Check this out:
There is another change that we found, when the pipeline rule is cloned:
![image](https://user-images.githubusercontent.com/23528701/39716313-66dcb790-5206-11e8-8ae6-41ecef484bec.png)

So now it works. 
Here it is the config for 2 pipelines, Infra.Build and Infra.Tests:
![image](https://user-images.githubusercontent.com/23528701/39716348-7d722c6a-5206-11e8-9cd8-21a9636482cb.png)

Infra.Tests have a custom message, while Infra.Build does not.

![image](https://user-images.githubusercontent.com/23528701/39716417-b057993a-5206-11e8-88f6-c7688140c79a.png)

So. I think it is working :D

**Comment by ashwanthkumar** [comment]
@hbsis-williamdasilva That's great! I generally accept Pull-Requests with the changes. You can read more about it at https://help.github.com/articles/creating-a-pull-request/

**Comment by ashwanthkumar** [comment]
Closing this as non-active issue.
