### ISSUE TITLE
Pipeline rules not correctly applying

### ISSUE THREAD

**Issue by MHP47** [ashwanthkumar/gocd-slack-build-notifier#73]
Using the rules from [pipeline-rules](https://github.com/ashwanthkumar/gocd-slack-build-notifier#pipeline-rules), it seems to be ignoring the "group" setting, and just matching all names (".*") and the state, then posting on that.

Trying to categorize pipelines based on groups, but it's not working as expected. Is there any log file that's generated for the plugin, or any way to get a debug log output?

Here is the conf file I am using (sensitive details removed):

`gocd.slack {`
`  login = "USERNAME"`
`  password = "PASSWORD"`
`  server-host = "SERVER_URL"`
`  api-server-host = "SERVER_URL"`
`  webhookUrl = "WEBHOOK_URL"`

`  # optional fields`
`  channel = "#gocd"`
`  slackDisplayName = "gocd-slack-bot"`
`  displayMaterialChanges = true`
`  proxy {`
`    hostname = "PROXY_DETAILS"`
`    port = "PORT"`
`    type = "http" # acceptable values are http / socks`
`  }`

`  pipelines = [{`
`    name = ".*"`
`    stage = ".*"`
`    group = ".*BI.*"`
`    state = "failed|cancelled|fixed|broken"`
`    channel = "#bi_gocd"`
`    webhookUrl = "WEBHOOK_URL"`
`  },`
`  {`
`    name = ".*"`
`    stage = ".*"`
`    group = ".*NAG.*"`
`    state = "failed|cancelled|fixed|broken"`
`    channel = "@USER"`
`    webhookUrl = "WEBHOOK_URL"`
`  },`
`  {`
`    name = ".*"`
`    stage = ".*"`
`    group = ".*"`
`    state = "all"`
`    channel = "#gocd"`
`    webhookUrl = "WEBHOOK_URL"`
`  }]`
`}`

But using the above, everything is being posted into the #bi_gocd channel, regardless of the assigned group. From the testing I've done, it seems to be ignoring the "group" setting, and just matching all names (".*") and the state, then posting on that

EDIT: Not everything being posted in #bi_gocd. "Building" and success status messages are being posted to #gocd, and all failures are going to #bi_gocd

**Comment by ashwanthkumar** [comment]
@MHP47 Can you please share the version of the plugin and the GoCD version you're using?

**Comment by MHP47** [comment]
Hey @ashwanthkumar, details below

Go Version: 16.10.0 (4131-730ff1867576754414cc632957f344d0263bc06d).
Slack Notification Plugin 1.4.0-RC7

**Comment by MHP47** [comment]
Ah, ok, bit more reading, looks like [#65](https://github.com/ashwanthkumar/gocd-slack-build-notifier/issues/65) is this issue. I will give the latest release a go, see if that fixes this :)

**Comment by MHP47** [comment]
@ashwanthkumar looks like gocd-slack-notifier-1.4.0-RC11.jar resolves this issue :+1:
