### ISSUE TITLE
Could not send message to slack: connect timed out

### ISSUE THREAD

**Issue by tonyzwei** [ashwanthkumar/gocd-slack-build-notifier#75]
Error: Interaction with plugin with id 'slack.task' implementing 'task' extension failed while requesting for 'execute'. Reason: [Could not send message to slack: connect timed out]took

But I ran a simple curl call to the webhook and it works.

The same pipeline job works for other Go agents of different networks. Any reason could it be?

**Comment by ashwanthkumar** [comment]
This repository houses the plugin with id [`slack.notifier`](https://github.com/ashwanthkumar/gocd-slack-build-notifier/blob/master/src/main/resources/plugin.xml#L2) and not `slack.task`. Looks like you're looking for a task plugin, while this repo holds the notification plugin. Can you please check and let me know?

**Comment by ashwanthkumar** [comment]
I guess the repository is https://github.com/Vincit/gocd-slack-task.

**Comment by ashwanthkumar** [comment]
Closing this as not an issue.
