### ISSUE TITLE
setup CRUISE_SERVER_DIR  and GO_NOTIFY_CONF

### ISSUE THREAD

**Issue by ndeztea** [ashwanthkumar/gocd-slack-build-notifier#77]
Hi,

I am new on goCD and I am trying to setup the notif to slack, I wont to know more detail how and where can i setup this configuration GO_NOTIFY_CONF and CRUISE_SERVER_DIR, please explain more..

thank you!

**Comment by ashwanthkumar** [comment]
Hopefully [this](https://docs.gocd.org/current/installation/install/server/linux.html#location-of-gocd-server-files) should help.
