### ISSUE TITLE
will plugin operate only on specified pipelines?

### ISSUE THREAD

**Issue by squatchBKLN** [ashwanthkumar/gocd-slack-build-notifier#78]
i have a question about the configuration of the plugin that was unclear to be from the documentation...

if my gocd server has 100 pipelines but i only want to receive slack notifications on failure to a small subset of them, is there a way to configure the plugin to do this.  for example, i have 5 jobs that i want notifications for but i want no communication at all for the other 95, does the plugin support this?

**Comment by ashwanthkumar** [comment]
@squatchBKLN Short answer - yes!

#### Long answer

In the default configuration that's shared in the README there's a section similar to below

```
 {
    name = ".*"
    stage = ".*"
    state = "failed"
  }
```

This change enables notifications for all the pipelines. Instead if you can put in the list of all pipeline, stage combinations you want to monitor. This plugin will only send notifications for that.
