### ISSUE TITLE
Plugin can't connect to Go server with authentication

### ISSUE THREAD

**Issue by pastafari** [ashwanthkumar/gocd-slack-build-notifier#8]
Hi @ashwanthkumar ,
Thanks for working on this plugin :smile:  
I keep seeing these lines in my logs
`Couldn't fetch build details: java.io.IOException: Server returned HTTP response code: 401`

So I poked around in the code a little bit. I realized that you're fetching history using the REST API, but this doesn't work when authentication is turned on. I also see that you're using `login` and `password` from the config file but this is not documented. So two questions really:
1. If login and password in conf is the right way to fix this, then can we add it to the docs - happy to send a PR.
2. This does however expose my Go password in plaintext on the server :( any way around that?

**Comment by ashwanthkumar** [comment]
Yeah, I forgot to update the docs. Happy to accept the PR :)

Regarding the password in plaintext. The password is stored on the server, If you're worried about your password. Why not create a separate account for slack plugin and use it? Is that an option?

**Comment by pastafari** [comment]
@ashwanthkumar yes creating a separate account is an option. What permissions would the account need to have since it uses the API?

**Comment by ashwanthkumar** [comment]
As long as the user's role has access to pipeline it should be fine.

**Comment by ashwanthkumar** [comment]
I'm closing this now. Feel free to re-open if you still have any issues.
