### ISSUE TITLE
How to see logs generated by the plugin?

### ISSUE THREAD

**Issue by pavelkostyurin** [ashwanthkumar/gocd-slack-build-notifier#84]
Hi!

Please, suggest.

Also, is there a way to get not only commit name, but also description (goCD correctly shows commit description in webGUI)

**Comment by ashwanthkumar** [comment]
The logs should be located along side the GoCD Sever logs. On linux, it's generally available under `/var/log/go-server`. It would be of the form `plugin-slack.notifier.log`. 

> Also, is there a way to get not only commit name, but also description (goCD correctly shows commit description in webGUI)

Can you please describe more on this? Does it mean, you want to show the commit message as well? Can you try setting `displayMaterialChanges` to `true` in the configuration and see if that's what you're looking for?

**Comment by pavelkostyurin** [comment]
Thanks, both questions are solved.

For full commit message to work, I had to swap `mod.summarizeComment();` with `mod.comment;` in `SlackPipelineListener` class.
