### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by frangte** [ashwanthkumar/gocd-slack-build-notifier#88]
![image](https://user-images.githubusercontent.com/19859575/46326110-7b541e00-c625-11e8-97d1-1b7cb7d03c51.png)

- Above is error after i repalace `.jar` file in `plugin/external` and restart GoCD.
- GoCD version is: 18.7

**Comment by ashwanthkumar** [comment]
@frangte Can you check the checksum of the file that you've downloaded? May be the download of the JAR failed or was corrupted? 

The SHA 256 checksum of the file should be 
```
3c2a3f706c3349360b65f9d0c531c6f1634fe3ed442d232b870fb2f67c78aca3  gocd-slack-notifier-1.4.0-RC11.jar
```

**Comment by frangte** [comment]
Yes. Thanks for you  reply. I try redownload and resolve my issue.
