### ISSUE TITLE
Send notifications to Microsoft Teams

### ISSUE THREAD

**Issue by harish123321** [ashwanthkumar/gocd-slack-build-notifier#91]
I want to send build information to Microsoft Teams from GOCD. Is there any way can I do it.

**Comment by ashwanthkumar** [comment]
@harish123321 We don't support Microsoft Teams right now. If you're willing to help, it should be easy to add that integration in here.

**Comment by ashwanthkumar** [comment]
@harish123321 We don't support Microsoft Teams right now. Let me know if you're willing to help by sending a PR. It should be easy to add that integration in here.

**Comment by sagrawal-myriad** [comment]
I was wondering if there is a push for this feature or if there is any other solution that could be used.

**Comment by ashwanthkumar** [comment]
I'm just going to put this out here, if someone is willing to help for this feature. You might need a parallel implementation of [this class](https://github.com/ashwanthkumar/gocd-slack-build-notifier/blob/master/src/main/java/in/ashwanthkumar/gocd/slack/SlackPipelineListener.java) for MS Teams. I would be happy to review any PRs regarding this.

**Comment by lukelast** [comment]
Hi @ashwanthkumar , I've started to work on this and would love some feedback if you have time.
https://github.com/lukelast/gocd-slack-build-notifier/commits/master

**Comment by jdavisp3** [comment]
Hi @ashwanthkumar , what do you think of the PR posted above?

**Comment by ashwanthkumar** [comment]
@jdavisp3 I did look at the commits on the fork and they look good. I haven't personally used Teams though so would need help in validating the changes in a real installation. For the changes to get merged, I would also need help with the documentation for the relevant bits.

**Comment by jdavisp3** [comment]
> @jdavisp3 I did look at the commits on the fork and they look good. I haven't personally used Teams though so would need help in validating the changes in a real installation. For the changes to get merged, I would also need help with the documentation for the relevant bits.

🆒 we can help with that. We will be testing in a real installation and can help with documentation.

**Comment by lukelast** [comment]
@ashwanthkumar I created a PR for Teams support.
https://github.com/ashwanthkumar/gocd-slack-build-notifier/pull/112

I took a stab at updating the readme. Please let me know if there's anything else I can do.

**Comment by ashwanthkumar** [comment]
Fixed via #112
